const NAME_SPACE = 'LOGIN';

const constants = {
  FETCH_LOGIN_REQUEST: `${NAME_SPACE}/FETCH_LOGIN_REQUEST`,
  FETCH_LOGIN_FAILURE: `${NAME_SPACE}/FETCH_LOGIN_FAILURE`,
  FETCH_LOGIN_SUCCESS: `${NAME_SPACE}/FETCH_LOGIN_SUCCESS`,
  FETCH_LOGIN: `${NAME_SPACE}/FETCH_LOGIN`,
  FETCH_LOGOUT_REQUEST: `${NAME_SPACE}/FETCH_LOGOUT_REQUEST`,
  FETCH_LOGOUT_FAILURE: `${NAME_SPACE}/FETCH_LOGOUT_FAILURE`,
  FETCH_LOGOUT_SUCCESS: `${NAME_SPACE}/FETCH_LOGOUT_SUCCESS`,
  FETCH_LOGOUT: `${NAME_SPACE}/FETCH_LOGOUT`,
}

export default constants;
