const NAME_SPACE = 'USERS';

const constants = {
  FETCH_USERS_REQUEST: `${NAME_SPACE}/FETCH_USERS_REQUEST`,
  FETCH_USERS_FAILURE: `${NAME_SPACE}/FETCH_USERS_FAILURE`,
  FETCH_USERS_SUCCESS: `${NAME_SPACE}/FETCH_USERS_SUCCESS`,
  FETCH_USERS: `${NAME_SPACE}/FETCH_USERS`,
  FETCH_SAVE_USER_REQUEST: `${NAME_SPACE}/FETCH_SAVE_USER_REQUEST`,
  FETCH_SAVE_USER_FAILURE: `${NAME_SPACE}/FETCH_SAVE_USER_FAILURE`,
  FETCH_SAVE_USER_SUCCESS: `${NAME_SPACE}/FETCH_SAVE_USER_SUCCESS`,
  FETCH_SAVE_USER: `${NAME_SPACE}/FETCH_SAVE_USER`,
}

export default constants;
